services:
  - type: web
    name: moodtracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn moodtracker_site.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: moodtracker_site.settings
      - key: PYTHON_VERSION
        value: 3.10
